
name: otus_hw13

on:
  push:
    branches: [ "main" ]
    paths:
     - 'hm13/**'
  pull_request:
    branches: [ "main" ]
    paths: 
     - 'hm13/**'

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install libeigen3-dev -y 
    - run: sudo apt install libgtest-dev
    - run: cmake ${{github.workspace}}/hm13 -DCMAKE_BUILD_TYPE="Release" -DPATCH_VERSION=${{ github.run_number }} 
    - run: cmake --build .
    - run: cmake --build . --target hw13_test
    - run: cmake --build . --target package    
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
      with:
        tag_name: hw12_${{ github.run_number }}
        release_number: Release  ${{ github.run_number }}
        draft: false
        prerelease: false
    - name: Upload build
      uses: actions/upload-artifact@v4 
      with:
        name: homework13
        path: /home/runner/work/otus_c_plus_hw13/otus_c_plus_hw12/
